config/routes.rb
Rouges::Application.routes.draw do
  root :to => 'home#home'
  get  'request/:service' => 'requests#new', :as => :request
  post 'request/:service' => 'requests#create', :as => :request
  resources 'services', only: [:index]
  resources 'districts', only: [:index]
end

app/models/area.rb
class Area < ActiveRecord::Base
  include ContainsPoint
end

app/models/district.rb
class District < ActiveRecord::Base
  include ContainsPoint

  def all_services
    events = Event.select(:type_code).where(:district_id => id).group(:type_code)
    events.map { |e| Easy311::Rails.filtered_services.find { |s| s.code == e.type_code } }.uniq
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :type_code, :presence => true, :inclusion => { :in =>
    proc { Easy311::Rails.filtered_services.map(&:code) } }

  validates :lonlat, presence: true

  attr_accessible :type_code, :lonlat

  before_save :set_district
  before_save :set_area

  belongs_to :district
  belongs_to :area

  def self.from_request(request)
    event = Event.new(
      :lonlat => "POINT(#{request.long.to_f} #{request.lat.to_f})",
      :type_code => request.service.code
    )
  end

  def lat
    lonlat.try(:y)
  end

  def lon
    lonlat.try(:x)
  end


  private

  def set_district
    self.district = District.contains_point(lat, lon)
  end

  def set_area
    self.area = Area.contains_point(lat, lon)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController

  def index
    @districts = District.all
  end

  def scores
    @districts = District.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @events = Event.where('created_at > ? ', 7.days.ago).to_json(methods: [:lat, :lon], only: [])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :validate_service, :only => [:new, :create]

  def new
    @request = Easy311::Request.new(service)
  end

  def create
    @request = Easy311::Request.new(service)
    @request.attributes = params[:request].except("password")

    if @request.valid?
      api_wrapper = Easy311::Rails.api_wrapper
      api_response = api_wrapper.send_request(@request)

      if api_response.invalid?
        flash.now[:alert] = api_response.error_message
        render 'new' and return
      end

      event = create_event(api_response)
      if event.save
        redirect_to(services_path, :notice => I18n.t('requests.success')) and return
      else
        flash.now[:alert] = I18n.t('requests.error') # TODO hard error message + log
      end
    else
      flash.now[:alert] = I18n.t('requests.errors_in_form')
    end
    render 'new'
  end

  private

  def validate_service
    unless service
      raise ActionController::RoutingError.new("Invalid service : #{params[:service]}")
    end
  end

  def service
    @service ||= Easy311::Rails.filtered_services.find do |service|
      service.code == params[:service]
    end
  end

  def create_event(api_response)
    Event.from_request(@request).tap do |event|
      event.token = api_response.token
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Easy311::Rails.filtered_services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
  def service_score(district, service)
    points = Easy311::Rails.points_for_area(district.name)
    nb_events = Event.where(:type_code => service.code).count()
    return nb_events * points
  end

  def total_district_score(district, services)
    services.map { |s| service_score(district, s) }.sum
  end
end

app/helpers/services_helper.rb
module ServicesHelper

  def service_config(code)
    Easy311::Rails.load_config['services'].select do |section|
      section['service_code'] == code
    end.first || {}
  end

  def service_name(service)
    config = service_config(service.code)
    if config.include? 'name'
      config['name']
    else
      service.name
    end
  end

  def service_css_class(service)
    config = service_config(service.code)
    return config['css_class'] if config.include? 'css_class'
    return service.name.parameterize
  end

  def service_desc(service)
    config = service_config(service.code)
    return config['description'] if config.include? 'description'
    return service.description
  end

  def service_input(form, code, attr)
    html = form.input(attr.code.to_sym,
      :label => attr.description,
      :placeholder => attr.description,
      :as => "easy311_#{attr.datatype}",
      :collection => attr.values,
      :label_method => lambda { |v| v['name'] },
      :value_method => lambda { |v| v['key'] },
      :required => attr.required,
      :input_html => { value: nil })

    #TODO: Find a cleaner way of deactivating the input than just hiding and submitting
    if prefill_date_input(code)
      return "<div class='hidden'>#{html}</div>".html_safe
    end
    return html
  end

  def prefill_date_input(code)
    Easy311::Rails.load_config['date_prefill'].include? code
  end

end

app/views/districts/index.html.erb
<% content_for(:back_url, '/') %>
<% content_for(:header_title, t('districts.signal')) %>
<div class="wrapper">
    <div id="st-accordion" class="st-accordion">
        <ul>
          <%
            mapping = @districts.map { |d| [total_district_score(d, d.all_services), d] }
            mapping = mapping.sort_by { |m| m[0] }.map { |m| m[1] }.reverse
          %>
          <% mapping.each do |district| %>
            <li>
            <%= link_to (district.name + '<span class="st-arrow">Open or Close</span>').html_safe, districts_path(district) %>
            <% services = district.all_services %>
              <span class="score"><%= total_district_score(district, services) %></span>
              <div class="st-content">
                <ul>
                  <% services.each do |service| %>
                    <li class="<%= service_css_class(service) %>"><%= service_name(service) %>
                    </li>
                  <% end %>
                </ul>
            </div>
            </li>
          <% end %>
        </ul>
    </div>
</div>
<script type="text/javascript">
    $(function() {
    
        $('#st-accordion').accordion({
            oneOpenedItem   : true
        });
        
    });
</script>

app/views/home/home.html.erb
<h1 class="logozone"><span class="logo"></span><span class="visuallyhidden"><%= t('app_title') %></span></h1>

<div class="callAction"><%= link_to(t('home.signal'), services_path) %></div>
<div class="districts"><%= link_to(t('districts.signal'), districts_path) %></div>
<script type="text/javascript">
  $(function() {
    $(document).trigger('homemap:ready', [<%= @events.html_safe %>]);
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport" content="width=device-width,user-scalable=no">

  <title><%= t('app_title') %></title>

  <link rel="apple-touch-icon-precomposed" href="/img/touch-icon.png" />
  <%= stylesheet_link_tag "application", :media => "all" %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= javascript_include_tag "application" %>

  <script type="text/javascript">
    // Apple wizardry to remove letterbox
    if (window.screen.height == 568) {
      document.querySelector("meta[name=viewport]").content="width=320.1";
    }
  </script>
</head>
<body class="controller-<%= params[:controller] %>">


<header class="navBar shadow">
  <div><%= link_to(t('nav.back'), content_for(:back_url), :class => 'navigation') %></div>
  <h1><%= content_for(:header_title) %></h1>
  <div></div>
</header>

  <% [:alert, :error, :notice].each do |key| %>
    <% if flash[key] %>
      <div class="flash flash-<%= key %>" data-alert="alert"><%= flash[key] %></div>
    <% end %>
  <% end %>

  <%= yield %>

  <div class="footer-disclaimer">
    Ce site web a été conçu lors des activités de la compétition Iron Web dans le cadre de la conférence WAQ. Les demandes envoyées ne seront pas réellement envoyées. Cette application est seulement une démonstration.
  </div>

</body>
</html>

app/views/requests/_form.html.erb
<%= simple_form_for(@request, :as => 'request', :url => request_path(@request.service)) do |form| %>
  <div class="map_zone">
    <button id="enlarge" type="button"><span aria-hidden="true" data-icon="&#xe000;"></span></button>
    <button id="minimize" type="button"><span aria-hidden="true" data-icon="&#xe001;"></span></button>
    <div id="map_canvas"></div>
  </div>
  <p id="localisation"></p>
  <div class="service-attributes">
    <div class="navBar">
      <h2><%= '• ' + t('requests.information') %></h2>
    </div>    
    <fieldset>
      <legend class="visuallyhidden"><%= t('requests.information') %></legend>
      <%= form.input :description, :placeholder => t('requests.description') %>
      <% @request.service.ordered_attrs.each do |code, attr| %>
          <%= service_input(form, code, attr) %>
      <% end %>
    </fieldset>
  </div>
  <div class="contact">
    <div class="navBar spacing">
      <h2><%= '• ' + t('requests.contact') %></h2>
    </div>
    <fieldset>
      <legend class="visuallyhidden"><%= t('requests.contact') %></legend>
      <%= form.input :email, :placeholder => t('requests.email') + "*", :required => true, :hint => 'Pour obtenir un retour sur votre demande, entrez votre courriel' %>
    </fieldset>
  </div>
  <fieldset id="register">
    <%= form.input :password, :placeholder => t('requests.password') %>
  </fieldset>
  <%= form.input :lat, as: :hidden %>
  <%= form.input :long, as: :hidden %>
  <%= form.submit t('requests.submit'), :id => 'request_submit', :class => 'navBar' %>
<% end %>

app/views/requests/new.html.erb
<% content_for(:back_url, services_path) %>
<% content_for(:header_title, service_name(@request.service)) %>
<%= render 'form' %>

app/views/services/index.html.erb
<% content_for(:back_url, '/') %>
<% content_for(:header_title, "Types d'anomalie") %>
<ul class="services">
  <% @services.each do |service| %>
    <li class="<%= service_css_class(service) %>"><%= link_to(service_name(service), request_path(service)) %></li>
  <% end %>
</ul>